apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c8-azure-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.camunda.io/
    chart: camunda-platform
    targetRevision: 8.3.2
    helm:
      values: |
        global:
          image:
            tag: 8.3.1
        zeebe:
          clusterSize: 1
          partitionCount: 1
          replicationFactor: 1
          pvcSie: 5Gi
        zeebe-gateway:
          replicas: 1
        elasticsearch:
          master:
            replicaCount: 1
            persistence:
              size: 15Gi
  destination:
    server: https://jens-clust-jens-rg-497cbe-vwfgpn3i.hcp.westeurope.azmk8s.io:443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true