apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c8-same-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.camunda.io/
    chart: camunda-platform
    targetRevision: 8.3.2
    helm:
      values: |
        global:
          image:
            tag: 8.3.0
  destination:
    server: https://kubernetes.default.svc
    namespace: camunda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true